<?php

namespace Database\Seeders;

use App\Models\MaintenanceManagement\Rooms;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('rooms')->insert([
            //Main Building Ground Flooor
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '1',
                'room_number' => 'CHE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSCHE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '2',
                'room_number' => 'CPE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSCPE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '3',
                'room_number' => 'CERE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSCERE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '4',
                'room_number' => 'AVR',
                'room_type' => '',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '5',
                'room_number' => 'ABE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSABE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '6',
                'room_number' => 'ME Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSME"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '7',
                'room_number' => 'iHUB',
                'room_type' => 'Laboratory / Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '8',
                'room_number' => 'COE 115',
                'room_type' => 'Laboratory Room',
                'department_priority' => json_encode(["BSCPE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => 'Ground Floor',
                'room_id' => '9',
                'room_number' => 'COE 116',
                'room_type' => 'Laboratory Room',
                'department_priority' => json_encode(["BSCPE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Main Building Second Floor
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '1',
                'room_number' => 'COE 215',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '2',
                'room_number' => 'COE 216',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '3',
                'room_number' => 'COE 217',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '4',
                'room_number' => 'COE 218',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '5',
                'room_number' => 'COE 219',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '6',
                'room_number' => 'COE 220',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '7',
                'room_number' => 'COE 222',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '8',
                'room_number' => 'COE 223',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '9',
                'room_number' => 'COE 224',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '10',
                'room_number' => 'COE 204',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '11',
                'room_number' => 'COE 205',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '12',
                'room_number' => 'COE 206',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '13',
                'room_number' => 'COE 207',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '14',
                'room_number' => 'COE 214',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '15',
                'room_number' => 'COE 213',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '16',
                'room_number' => 'COE 212',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '17',
                'room_number' => 'COE 211',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '18',
                'room_number' => 'COE 210 B',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '19',
                'room_number' => 'COE 209 and 210 A',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '20',
                'room_number' => 'COE 208',
                'room_type' => 'Lecture Room',
                'department_priority' => '',
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '21',
                'room_number' => 'ECE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSECE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'Main Building',
                'floor' => '2nd Floor',
                'room_id' => '22',
                'room_number' => 'EE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSEE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //New building ground floor
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '1',
                'room_number' => 'CE Dept',
                'room_type' => 'Faculty Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '2',
                'room_number' => 'NB Room 1',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '3',
                'room_number' => 'NB Room 2',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '4',
                'room_number' => 'NB Room 3',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '5',
                'room_number' => 'NB Room 4',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '6',
                'room_number' => 'NB Room 5',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => 'Ground Floor',
                'room_id' => '7',
                'room_number' => 'NB Room 6',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //2nd floor
            [
                'building' => 'New Building Phase 1',
                'floor' => '2nd Floor',
                'room_id' => '1',
                'room_number' => 'CAD Room 3',
                'room_type' => 'Laboratory Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => '2nd Floor',
                'room_id' => '2',
                'room_number' => 'CAD Room 2',
                'room_type' => 'Laboratory Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => '2nd Floor',
                'room_id' => '3',
                'room_number' => 'CAD Room 1',
                'room_type' => 'Laboratory Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'building' => 'New Building Phase 1',
                'floor' => '2nd Floor',
                'room_id' => '4',
                'room_number' => 'NB Room 7',
                'room_type' => 'Lecture Room',
                'department_priority' => json_encode(["BSCE"]),
                'is_active' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
