<?php

namespace Database\Seeders;

use App\Models\Curriculum\CourseScheduling;
use Egulias\EmailValidator\Result\Reason\UnusualElements;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SchedulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $schedules = [
            //2024-2025 2nd Semester BSCPE 4-A
            [
                'id' => '1',
                'title' => 'CPE 199',
                'startTime' => '08:30:00',
                'endTime' => '10:00:00',
                'SubjectName' => 'Seminars and Fieldtrips',
                'color' => '#0D1D64',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Vladimir Ibañez',
                'daysOfWeek' => json_encode([2]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '1231',
                'title' => 'CPE 199',
                'startTime' => '08:30:00',
                'endTime' => '10:00:00',
                'SubjectName' => 'Seminars and Fieldtrips',
                'color' => '#0D1D64',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Vladimir Ibañez',
                'daysOfWeek' => json_encode([4]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2',
                'title' => 'CPE 182',
                'startTime' => '11:00:00',
                'endTime' => '12:30:00',
                'SubjectName' => 'Microelectronics III',
                'color' => '#417B37',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Diana Rose Tambogon',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2321',
                'title' => 'CPE 182',
                'startTime' => '11:00:00',
                'endTime' => '12:30:00',
                'SubjectName' => 'Microelectronics III',
                'color' => '#417B37',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Diana Rose Tambogon',
                'daysOfWeek' => json_encode([3]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3',
                'title' => 'SOCSC 03',
                'startTime' => '10:00:00',
                'endTime' => '11:00:00',
                'SubjectName' => 'The Contemporary World',
                'color' => '#FF5090',
                'label' => null,
                'room' => 'CAB 203',
                'teacher' => 'Ms. Lorma Cuadro',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '4',
                'title' => 'ENGG 101',
                'startTime' => '14:00:00',
                'endTime' => '15:00:00',
                'SubjectName' => 'Technopreneurship',
                'color' => '#9835AF',
                'label' => null,
                'room' => 'COE 215',
                'teacher' => 'Engr. Marifaye Flores',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '423',
                'title' => 'ENGG 101',
                'startTime' => '14:00:00',
                'endTime' => '15:00:00',
                'SubjectName' => 'Technopreneurship',
                'color' => '#9835AF',
                'label' => null,
                'room' => 'COE 215',
                'teacher' => 'Engr. Marifaye Flores',
                'daysOfWeek' => json_encode([3]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '5',
                'title' => 'ENGG 101',
                'startTime' => '11:00:00',
                'endTime' => '14:00:00',
                'SubjectName' => 'Technopreneurship',
                'color' => '#9835AF',
                'label' => 'Lab',
                'room' => 'iHUB',
                'teacher' => 'Engr. Marifaye Flores',
                'daysOfWeek' => json_encode([4]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6',
                'title' => 'SOCSC 03',
                'startTime' => '10:00:00',
                'endTime' => '11:00:00',
                'SubjectName' => 'The Contemporary World',
                'color' => '#FF5090',
                'label' => null,
                'room' => 'CAB 203',
                'teacher' => 'Ms. Lorma Cuadro',
                'daysOfWeek' => json_encode([3]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7',
                'title' => 'SOCSC 03',
                'startTime' => '10:00:00',
                'endTime' => '11:00:00',
                'SubjectName' => 'The Contemporary World',
                'color' => '#FF5090',
                'label' => null,
                'room' => 'CAB 203',
                'teacher' => 'Ms. Lorma Cuadro',
                'daysOfWeek' => json_encode([5]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8',
                'title' => 'TCEP 1',
                'startTime' => '14:00:00',
                'endTime' => '17:00:00',
                'SubjectName' => 'Technical Competency and Enchantment Program I',
                'color' => '#1350b8',
                'label' => null,
                'room' => 'iHUB',
                'teacher' => 'Engr. Edwin F. Galutira',
                'daysOfWeek' => json_encode([2]),
                'section' => 'BSCPE 4-A',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //End 2024-2025 2nd Semester BSCPE 4-A

            //2024-2025 2nd Semester BSCPE 4-B
            [
                'id' => '9',
                'title' => 'TCEP 1',
                'startTime' => '13:00:00',
                'endTime' => '15:00:00',
                'SubjectName' => 'Technical Competency and Enchantment Program I',
                'color' => '#7C4F82',
                'label' => null,
                'room' => 'iHUB',
                'teacher' => 'Engr. Edwin F. Galutira',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '10',
                'title' => 'CPE 182',
                'startTime' => '9:30:00',
                'endTime' => '11:00:00',
                'SubjectName' => 'Microelectronics III',
                'color' => '#7CD32A',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Diana Rose Tambogon',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '11',
                'title' => 'CPE 182',
                'startTime' => '9:30:00',
                'endTime' => '11:00:00',
                'SubjectName' => 'Microelectronics III',
                'color' => '#7CD32A',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Diana Rose Tambogon',
                'daysOfWeek' => json_encode([3]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '12',
                'title' => 'SOCSC 03',
                'startTime' => '11:00:00',
                'endTime' => '12:00:00',
                'SubjectName' => 'The Contemporary World',
                'color' => '#932437',
                'label' => null,
                'room' => 'CAB 203',
                'teacher' => 'Ms. Lorma Cuadro',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '13',
                'title' => 'SOCSC 03',
                'startTime' => '11:00:00',
                'endTime' => '12:00:00',
                'SubjectName' => 'The Contemporary World',
                'color' => '#932437',
                'label' => null,
                'room' => 'CAB 203',
                'teacher' => 'Ms. Lorma Cuadro',
                'daysOfWeek' => json_encode([3]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '14',
                'title' => 'SOCSC 03',
                'startTime' => '11:00:00',
                'endTime' => '12:00:00',
                'SubjectName' => 'The Contemporary World',
                'color' => '#932437',
                'label' => null,
                'room' => 'CAB 203',
                'teacher' => 'Ms. Lorma Cuadro',
                'daysOfWeek' => json_encode([5]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '15',
                'title' => 'ENGG 101',
                'startTime' => '15:00:00',
                'endTime' => '16:30:00',
                'SubjectName' => 'Technopreneurship',
                'color' => '#2FC1BA',
                'label' => '',
                'room' => 'COE 215',
                'teacher' => 'Engr. Marifaye Flores',
                'daysOfWeek' => json_encode([1]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '16',
                'title' => 'ENGG 101',
                'startTime' => '15:00:00',
                'endTime' => '16:30:00',
                'SubjectName' => 'Technopreneurship',
                'color' => '#2FC1BA',
                'label' => '',
                'room' => 'COE 215',
                'teacher' => 'Engr. Marifaye Flores',
                'daysOfWeek' => json_encode([3]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '17',
                'title' => 'ENGG 101',
                'startTime' => '11:00:00',
                'endTime' => '14:00:00',
                'SubjectName' => 'Technopreneurship',
                'color' => '#2FC1BA',
                'label' => 'Lab',
                'room' => 'iHUB',
                'teacher' => 'Engr. Marifaye Flores',
                'daysOfWeek' => json_encode([2]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '18',
                'title' => 'CPE 199',
                'startTime' => '15:00:00',
                'endTime' => '16:30:00',
                'SubjectName' => 'Seminars and Fieldtrips',
                'color' => '#0D1D64',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Vladimir Ibañez',
                'daysOfWeek' => json_encode([2]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '19',
                'title' => 'CPE 199',
                'startTime' => '15:00:00',
                'endTime' => '16:30:00',
                'SubjectName' => 'Seminars and Fieldtrips',
                'color' => '#0D1D64',
                'label' => null,
                'room' => 'COE 217',
                'teacher' => 'Engr. Vladimir Ibañez',
                'daysOfWeek' => json_encode([4]),
                'section' => 'BSCPE 4-B',
                'student_count' => 0,
                'course' => 'BSCPE',
                'year' => '2024',
                'semester' => '2nd Semester',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($schedules as $schedule) {
            DB::table('schedules')->insert($schedule);
            app('App\Http\Controllers\Curriculum\CourseSchedulingController')->updateAllConflicts($schedule['room'], $schedule['year'], $schedule['semester']);
        }
    }
}
